### ISSUE TITLE
Feature Request: Add STON.fi Integration to Tonutils

### ISSUE THREAD

**Issue by ethene** [nessshon/tonutils#11]
I would like to request the integration of STON.fi’s API (both v1 and v2) into the Tonutils library. This would allow users to interact with STON.fi directly, enabling swaps, liquidity provision, and referral management.

	•	STON.fi API v2 Reference: [Link](https://docs.ston.fi/docs/developer-section/api-reference-v2)
	•	STON.fi API v1 Reference: [Link](https://docs.ston.fi/docs/developer-section/api-reference-v1)

Adding this feature would enhance Tonutils by integrating DeFi capabilities on TON.

**Comment by nessshon** [comment]
Added swaps, nothing else is planned yet.
