### ISSUE TITLE
py.typed is missing in package

### ISSUE THREAD

**Issue by bshelkhonov** [nessshon/tonutils#13]
https://pypi.org/project/tonutils/0.1.5/#files - it is missing in distribution, probably because setuptools include it by default only since 69 version.

<img width="749" alt="image" src="https://github.com/user-attachments/assets/f1b8e377-3d2b-4fb2-9fc8-9ffce1a516fd">

**Comment by nessshon** [comment]
@bshelkhonov Thank you for pointing this out! The issue has been resolved in version `0.1.6`.
