### ISSUE TITLE
Cannot connect to host testnet.tonapi.io:443 ssl:True

### ISSUE THREAD

**Issue by asvechkar** [nessshon/tonutils#14]
Execute code: https://github.com/nessshon/tonutils/blob/main/examples/wallet/common/transfer_ton.py

Error:

raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host testnet.tonapi.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]

**Comment by Navipro70** [comment]
I've tried run `/Applications/Python\ 3.12/Install\ Certificates.command`, and error was gone. But now it's new error appeared with `code = Cell.one_from_boc(result["code"])` in tonapi and toncenter client. Did you found a solution?

**Comment by nessshon** [comment]
@Navipro70 Make sure the contract address is deployed and the network is selected correctly (tesnet or mainnet)

**Comment by Navipro70** [comment]
@nessshon idk but if address is undeployed and we trying to get address (balance or raw account), it will catch an exception and it's logically. Code of smart contract for that address is not exists and backend didn't return code field, which creates that exception)))

**Comment by Navipro70** [comment]
@nessshon does this repo has methods to check that address is undeployed?
