### ISSUE TITLE
Transfer a nft

### ISSUE THREAD

**Issue by Sanchoyzer** [nessshon/tonutils#16]
I'm following an [example](https://github.com/nessshon/tonutils/blob/main/examples/nft/transfer_nft.py), and the code works successfully, but the transfer isn't executed: there is a bounce.
There is a manual nft transfer:
![20](https://github.com/user-attachments/assets/de9efb4b-d409-45a3-a2ad-e81b4d0cbab9)
This is my transfer:
![10](https://github.com/user-attachments/assets/feedd5ff-661a-4584-8bbe-6e4444aca48b)
What could be a problem?

Perhaps, the reason is
```
Compute Phase
Skipped:
true
Skip Reason:
cskip_no_state
```

**Comment by nessshon** [comment]
@Sanchoyzer Send a link to the transaction.

**Comment by Sanchoyzer** [comment]
@nessshon , the [link](https://tonviewer.com/transaction/caa585f9ace00aa0dff95873ed7cfa53fa4caa0e82589f6ff64e9224305af0c9)

**Comment by nessshon** [comment]
@Sanchoyzer NFT_ADDRESS invalid, uninitiated contract...
![Screenshot_20241109-023423_Chrome](https://github.com/user-attachments/assets/65124f47-736c-4a23-9d92-ba5640707935)

**Comment by Sanchoyzer** [comment]
@nessshon , I tried to connect [mint](https://github.com/nessshon/tonutils/blob/main/examples/nft/mint_onchain_nft.py) and [transfer](https://github.com/nessshon/tonutils/blob/main/examples/nft/transfer_nft.py) examples:

```python
# create a nft
nft = NFTEditableModified(...)
body = CollectionEditableModified.build_mint_body(
    index=NFT_INDEX,
    owner_address=Address(OWNER_ADDRESS),
    content=NFTModifiedOnchainContent(...),
)
_ = await wallet.transfer(...)
nft_address = nft.address.to_str()
assert nft_address.startswith('EQ')

# transfer this nft
body = NFTStandard.build_transfer_body(
    new_owner_address=Address(NEW_OWNER_ADDRESS),
    forward_payload=(...),
    forward_amount=1,
)
_ = await wallet.transfer(
    destination=nft_address,  # incorrect nft address => bounce
    amount=0.05,
    body=body,
)
```

This `nft_address` value is wrong: it's impossible to find this nft by the address on Getgems, and impossible to transfer.
The real nft address is different, and I don't know how to get it.
