### ISSUE TITLE
Dont work v2 swap on ston.fi

### ISSUE THREAD

**Issue by stufently** [nessshon/tonutils#23]
Use this code https://github.com/nessshon/tonutils/blob/main/examples/jetton/dex/stonfi/v2/swap_ton_to_jetton.py
Try swap ton to  major 
https://app.ston.fi/swap?chartVisible=false&ft=TON&tt=MAJOR

# Address of the Jetton Master for swapping
TO_JETTON_MASTER_ADDRESS = "EQCuPm01HldiduQ55xaBF_1kaW_WAUy5DHey8suqzU_MAJOR"  # 

# Number of decimal places for the Jetton
JETTON_DECIMALS = 9

# Amount of TON to swap (in base units, considering decimals)
TON_AMOUNT = 0.1

Example transaction 
https://tonviewer.com/UQClY81dCu9tE2zqeM2jygPfxNXEiINnx0i-ocKR6WxC2jWl

Seems sdk generate not  right contract call

**Comment by nessshon** [comment]
@stufently try to specify this router address `EQCDT9dCT52pdfsLNW0e6qP5T3cgq7M4Ug72zkGYgP17tsWD`.

```python
to, value, body = await StonfiRouterV2(client, router_address=Address("EQCDT9dCT52pdfsLNW0e6qP5T3cgq7M4Ug72zkGYgP17tsWD")).get_swap_ton_to_jetton_tx_params(...)
```

**Comment by stufently** [comment]
its work thnx 
how get router address for another jetton  and for v1 pools?

**Comment by nessshon** [comment]
@stufently You can find the router address on the page https://api.ston.fi/swagger-ui/#/Dex/dex_simulate_swap. If you are exchanging TON for Jetton, the `offer_address` parameter should contain the master address of the pTON token. Specify the desired token in the `ask_address` field, execute the request, and the response will include the `router_address` field that you need to use.

I recommend reviewing the Stonfi documentation for more information.

**Comment by stufently** [comment]
Good idea add it to examples code 
https://github.com/nessshon/tonutils/blob/main/examples/jetton/dex/stonfi/v2/swap_ton_to_jetton.py
