### ISSUE TITLE
How check blance

### ISSUE THREAD

**Issue by Menmaz** [nessshon/tonutils#4]
Is there a feature to checkBlance jetton or ton
Also currently the addresses all start with UD, how to make the result show as UD instead of EQ.
Thank you.

**Comment by TacoBel42** [comment]
same question

**Comment by Menmaz** [comment]
> same question

use code : 
`
url=https://toncenter.com/api/v3/jetton/wallets?owner_address={you_address}&jetton_address={jetton_need_check}&limit=128&offset=0
`

**Comment by nessshon** [comment]
@Menmaz Added examples:
Get wallet balance: https://github.com/nessshon/tonutils/blob/main/examples/wallet/get_balance.py
Get jetton wallet balance: https://github.com/nessshon/tonutils/blob/main/examples/jetton/get_balance.py

**Comment by 0xBezaLeL** [comment]
> @Menmaz Added examples: Get wallet balance: https://github.com/nessshon/tonutils/blob/main/examples/wallet/get_balance.py Get jetton wallet balance: https://github.com/nessshon/tonutils/blob/main/examples/jetton/get_balance.py

im trying 

`async def main() -> None:
    client = TonapiClient(api_key=API_KEY, is_testnet=IS_TESTNET)

    jetton_wallet_address = await JettonMaster.get_wallet_address(
        client=client,
        owner_address=OWNER_ADDRESS,
     
        jetton_master_address=JETTON_MASTER_ADDRESS,
    )

    jetton_wallet_data = await JettonWallet.get_wallet_data(
        client=client,
        jetton_wallet_address=jetton_wallet_address,
    )

    print(f"Jetton wallet balance (nano): {jetton_wallet_data.balance}")
    print(f"Jetton wallet balance (Jettons): {to_amount(jetton_wallet_data.balance, JETTON_DECIMALS)}")`
    
 but got error 
 
 
 `Traceback (most recent call last):
  File "/Users/bezalel/project/erDropCuy/TON_Project/jettons_sender/jettons_balance.py", line 44, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/bezalel/project/erDropCuy/TON_Project/jettons_sender/jettons_balance.py", line 25, in main
    jetton_wallet_address = await JettonMaster.get_wallet_address(
  File "/Users/bezalel/project/erDropCuy/TON_Project/jettons_sender/venv/lib/python3.10/site-packages/tonutils/jetton/contract/standard/master.py", line 135, in get_wallet_address
    result = Address(method_result["decoded"]["jetton_wallet_address"])
KeyError: 'decoded'`

please help how to solve it.

thanks

**Comment by nessshon** [comment]
@0xBezaLeL Are you trying to get your hamster balance?

**Comment by 0xBezaLeL** [comment]
> https://toncenter.com/api/v3/jetton/wallets?owner_address={you_address}&jetton_address={jetton_need_check}&limit=128&offset=0

yes just for example cos its still hype right know...

**Comment by nessshon** [comment]
@0xBezaLeL Can you send me your wallet address via PM telegram nessshon.t.me?

**Comment by 0xBezaLeL** [comment]
let me contact you on telegram 
Thanks

**Comment by nessshon** [comment]
@0xBezaLeL The issue is that you're trying to retrieve the balance of Hamster tokens, which use the new mintless jetton standard. To resolve this, I recommend using the `pytonapi` library.

Here’s an example code snippet:

```python
"""pip install pytonapi"""
from pprint import pprint
from pytonapi import AsyncTonapi

# API key for accessing the Tonapi (obtainable from https://tonconsole.com)
API_KEY = "AE33...BD5I"

# The address of the owner
OWNER_ADDRESS = "UQ..."

async def main() -> None:
    tonapi = AsyncTonapi(API_KEY, debug=True)

    balances = await tonapi.accounts.get_jettons_balances(
        account_id=OWNER_ADDRESS,
        supported_extensions=["custom_payload"],
    )
    pprint(balances.model_dump(exclude_none=True))

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
```

**Comment by 0xBezaLeL** [comment]
> @0xBezaLeL The issue is that you're trying to retrieve the balance of Hamster tokens, which use the new mintless jetton standard. To resolve this, I recommend using the `pytonapi` library.
> 
> Here’s an example code snippet:
> 
> ```python
> """pip install pytonapi"""
> from pprint import pprint
> from pytonapi import AsyncTonapi
> 
> # API key for accessing the Tonapi (obtainable from https://tonconsole.com)
> API_KEY = "AE33...BD5I"
> 
> # The address of the owner
> OWNER_ADDRESS = "UQ..."
> 
> async def main() -> None:
>     tonapi = AsyncTonapi(API_KEY, debug=True)
> 
>     balances = await tonapi.accounts.get_jettons_balances(
>         account_id=OWNER_ADDRESS,
>         supported_extensions=["custom_payload"],
>     )
>     pprint(balances.model_dump(exclude_none=True))
> 
> if __name__ == "__main__":
>     import asyncio
>     asyncio.run(main())
> ```

oh okay, thanks for help...

**Comment by bupabupala** [comment]
> @0xBezaLeL The issue is that you're trying to retrieve the balance of Hamster tokens, which use the new mintless jetton standard. To resolve this, I recommend using the `pytonapi` library.
> 
> Here’s an example code snippet:
> 
> ```python
> """pip install pytonapi"""
> from pprint import pprint
> from pytonapi import AsyncTonapi
> 
> # API key for accessing the Tonapi (obtainable from https://tonconsole.com)
> API_KEY = "AE33...BD5I"
> 
> # The address of the owner
> OWNER_ADDRESS = "UQ..."
> 
> async def main() -> None:
>     tonapi = AsyncTonapi(API_KEY, debug=True)
> 
>     balances = await tonapi.accounts.get_jettons_balances(
>         account_id=OWNER_ADDRESS,
>         supported_extensions=["custom_payload"],
>     )
>     pprint(balances.model_dump(exclude_none=True))
> 
> if __name__ == "__main__":
>     import asyncio
>     asyncio.run(main())
> ```

Thanks for your guidance, brother. There are too few reference materials about TON.. After upgrading to the latest version of pytonapi based on your advice, I can indeed check the balance, but how do I use Jetton to make transfers?....Forgive me, my English was translated by GPT.
`class TonUtil:
    def __init__(self, address, mnemonic=None):
        self.tonapi = AsyncTonapi(api_key=TON_API_KEY,debug=True)
        self.client = TonapiClient(api_key=TON_API_KEY, is_testnet=False,)

        self.address = address

    async def get_token_balance(self, address,token: JETTON_MASTER_ADDRESS) -> JettonBalance:
        balances = await self.tonapi.accounts.get_jetton_balance(address, jetton_id=token.HMSTER,
                                                                 supported_extensions=["custom_payload"])

        logger.info(f"{token.name} 余额: {balances}")

        return balances

    async def get_info(self,address) -> Account:
        # 查询账户基本信息
        account_info = await self.tonapi.accounts.get_info(address)

        # 提取 TON 余额
        logger.info(f"TON 余额: {account_info}")
        return account_info

    async def transfer_ton(self, mnemonic: [], tranf_bean: TransferData):
        '''
        :param mnemonic:
        :param tranf_bean:
        :return:
        '''
        wallet, public_key, private_key, mnemonic = WalletV4R2.from_mnemonic(self.client, mnemonic)

        tx_hash = await wallet.transfer(
            destination=tranf_bean.destination,
            amount=tranf_bean.amount,
            body=tranf_bean.body,
        )
        logger.success(f"Successfully transferred {tranf_bean.amount} TON!")
        logger.success(f"Transaction hash: {tx_hash}")
        return tx_hash

    async def transfer_token(self, mnemonics: [], tranf_bean: TransferJettonData):
        '''
        :param mnemonic:
        :param tranf_bean:
        :return:
        '''
        wallet, public_key, private_key, mnemonic = WalletV4R2.from_mnemonic(self.client, mnemonics)

        tx_hash = await wallet.transfer_jetton(
            destination=tranf_bean.destination,
            jetton_master_address=tranf_bean.jetton_master_address,
            jetton_amount=tranf_bean.jetton_amount,
            jetton_decimals=tranf_bean.jetton_decimals,
            forward_payload=tranf_bean.forward_payload,
        )

        print(f"Successfully transferred {tranf_bean.jetton_amount} jettons!")
        print(f"Transaction hash: {tx_hash}")
        return tx_hash

    async def active_wallet(self,mnemonics: []):
        wallet, public_key, private_key, mnemonic = WalletV4R2.from_mnemonic(self.client, mnemonics)

        # Uncomment and use the following lines to create different wallet versions from mnemonic:
        # wallet, public_key, private_key, mnemonic = WalletV3R1.from_mnemonic(client, MNEMONIC)
        # wallet, public_key, private_key, mnemonic = WalletV3R2.from_mnemonic(client, MNEMONIC)
        # wallet, public_key, private_key, mnemonic = WalletV4R1.from_mnemonic(client, MNEMONIC)
        # wallet, public_key, private_key, mnemonic = WalletV4R2.from_mnemonic(client, MNEMONIC)
        # wallet, public_key, private_key, mnemonic = WalletV5R1.from_mnemonic(client, MNEMONIC)
        # wallet, public_key, private_key, mnemonic = HighloadWalletV2.from_mnemonic(client, MNEMONIC)
        # wallet, public_key, private_key, mnemonic = HighloadWalletV3.from_mnemonic(client, MNEMONIC)
        # wallet, public_key, private_key, mnemonic = PreprocessedWalletV2.from_mnemonic(client, MNEMONIC)
        # wallet, public_key, private_key, mnemonic = PreprocessedWalletV2R1.from_mnemonic(client, MNEMONIC)

        tx_hash = await wallet.deploy()

        logger.success(f"Wallet deployed successfully!")
        logger.success(f"Wallet address: {wallet.address.to_str()}")
        logger.success(f"Transaction hash: {tx_hash}")
        return tx_hash`

This is the transfer_token method I wrote based on your guidance, but the call failed... I don't know where the problem is. As a beginner, I really don't know how to fix it. Thank you."[this is chain msg](https://tonviewer.com/transaction/a994c88184099f5afba08035a6a1e9cc5e23ae80fecbac4e855069497af02ef0)

**Comment by nessshon** [comment]
@bupabupala The Hamster Jetton is a new standard for Mintless Jettons. To deploy and claim the tokens, you'll need to provide a `custom_payload`.

You can read more about it here: [Mintless Jetton Documentation](https://github.com/ton-community/mintless-jetton).

This example might be helpful: [Transfer Jetton Example](https://github.com/nessshon/tonutils/blob/97561e241e13fc3d8bb744f5cd3a68bcf97e472a/examples/jetton/transfer_jetton.py#L46). Just replace `forward_payload` with the correctly constructed `custom_payload`.

I haven’t looked into it much yet, but there might be useful information here: https://proof.hamsterkombatgame.io/jettons/EQAJ8uWd7EBqsmpSWaRdf_I-8R8-XHwh3gsNKhy-UrdrPcUo/wallet/{wallet_address}.

Extract the `custom_payload` and set it in the code like this: `custom_payload = Cell.one_from_boc("te6ccgECMwEABGkAAQgN9gLWAQlGA0I0rXIU3k...")`.

You’ll also need to provide `state_init`.

**Comment by nessshon** [comment]
@bupabupala I do not have such a wallet with Mintless Jetton to test and write instructions for transfer.

If you could share the wallet seed phrase, I would try to write instructions for translating Mintless Jetton Hamster.

If you are ready to provide, write to PM nessshon.t.me

**Comment by bupabupala** [comment]
> nessshon.t.me
I can provide you with test account. You can contact me or give me an email, and I'll send you the mnemonic phrases for wallets
https://t.me/eth_9271

**Comment by nessshon** [comment]
An example of transferring a mintless jetton is ready and available at https://github.com/nessshon/tonutils/blob/main/examples/jetton/transfer_mintless_jetton.py

**Comment by bupabupala** [comment]
> An example of transferring a mintless jetton is ready and available at https://github.com/nessshon/tonutils/blob/main/examples/jetton/transfer_mintless_jetton.py

thanks,I tried using your example and it showed 'Transaction hash: c8211799147ae4ef523153fa584669604634dfbf156021c971b6202ca3a448c4', but the final result was a failure. This is the result，[tranf result](https://tonviewer.com/transaction/c8211799147ae4ef523153fa584669604634dfbf156021c971b6202ca3a448c4), What caused this error? 。。。

**Comment by bupabupala** [comment]
> An example of transferring a mintless jetton is ready and available at https://github.com/nessshon/tonutils/blob/main/examples/jetton/transfer_mintless_jetton.py

I can provide you with some wallets that contain 'hamster' tokens for you to use if you need. you project is the best one I've used so far—it's very simple and clear

**Comment by nessshon** [comment]
@bupabupala Thanks! Try increasing amount to 0.1 or 0.2...
https://github.com/nessshon/tonutils/blob/799b9bc65264dc2508da81c62ae14c8692f20240/examples/jetton/transfer_mintless_jetton.py#L63

**Comment by bupabupala** [comment]
> @bupabupala Thanks! Try increasing amount to 0.1 or 0.2...
> 
> https://github.com/nessshon/tonutils/blob/799b9bc65264dc2508da81c62ae14c8692f20240/examples/jetton/transfer_mintless_jetton.py#L63
> 
> You must also make sure that you have this amount on your balance.

sorry... i have success  thanks
