### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Menmaz** [nessshon/tonutils#5]
500, message='LITE_SERVER_UNKNOWN: cannot apply external message to current state : External message was not accepted\nCannot run message on account: inbound external message rejected by transaction 022F22C83316F1F1E01CFF7F96272548E3A212054DA724F0DB7A537FD636A44A:\nexitcode=0, steps=0, gas_used=0', url=URL('https://toncenter.com/api/v3/message')
This error occurs in non-activated wallets. Therefore, it is impossible to find the seqno of that wallet. The solution is to set seqno=-1 or 0 .
Hope you fix it soon

**Comment by Menmaz** [comment]
I'm not sure my solution is correct :))

**Comment by Menmaz** [comment]
Update: Need to deploy contract and send a very small amount of ton to another address to activate wallet

**Comment by nessshon** [comment]
@Menmaz That's right! First you need to deploy the wallet by calling `wallet.deploy()`.
