### ISSUE TITLE
Get method "seqno" for account Address<EQ...> returned exit code 11

### ISSUE THREAD

**Issue by mix-protocol** [nessshon/tonutils#6]
Thanks for this library, I'm trying to run some swaps on DeDust but to no avail. The steps I've taken are:

```python
client = LiteClient(trust_level=2)
wallet, public_key, private_key, _ = HighloadWalletV3.from_mnemonic(client, MNEMONIC)

await wallet.deploy()    # deploy once

tx_hash = await wallet.batch_dedust_swap_ton_to_jetton(
    data_list=[
        SwapTONToJettonData(
            jetton_master_address="EQCvxJy4eG8hyHBFsZ7eePxrRsUQSFE_jpptRAYBmcG_DOGS",    # DOGS
            ton_amount=0.01,
        ),
        SwapTONToJettonData(
            jetton_master_address="EQBZ_cafPyDr5KUTs0aNxh0ZTDhkpEZONmLJA2SNGlLm4Cko",    # REDO
            ton_amount=0.01,
        ),
    ]
)
```

The above code, however, raises a RunGetMethodError exception with message `Get method "seqno" for account Address<EQ...> returned exit code 11`.  A similar `wallet.get_seqno(client, wallet.address.to_str())` call raises the same exception. Are there any further steps required?

**Comment by nessshon** [comment]
@mix-protocol wallet.deploy() only needs to be executed once, the first time you deploy your wallet.

**Comment by nessshon** [comment]
@mix-protocol Strange, highload wallet v3 doesn't have seqno. I just checked and everything works for me https://tonviewer.com/transaction/22a522b63b23f6ad6700c2f44194cafaa56faad0a85eb8a21a664d40f079c485
try updating the library version to the latest.

**Comment by mix-protocol** [comment]
many thanks! just gave it a go and managed to send my 1st tx on TON
side question: i understand seqno is similar to nonce in evm, in this case without seqno do u know what prevents replay attacks?
