### ISSUE TITLE
Error Transferring funds

### ISSUE THREAD

**Issue by bohd4nx** [nessshon/tonutils#9]
Error: 406, message='error code: 0 message: cannot apply external message to current state : External message was not accepted\nCannot run message on account: inbound external message rejected by account 067B65492412494449547598E28191FECDD68EC5358DF46EAE63D9ACC8EADEAC before smart-contract execution', url=URL('https://tonapi.io/v2/blockchain/message')

**Comment by nessshon** [comment]
@bohd4nx Need more info, wallet address, wallet version, is there a balance and is the wallet deployed..

**Comment by bohd4nx** [comment]
@nessshon Эта ошибка сама по себе лезет, возможно из-за неправильной настройки seqno
